# Generated by Django 6.0.3 on 2026-03-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodebaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('path', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('base_classes', models.TextField(blank=True, null=True)),
                ('is_final', models.IntegerField(default=0)),
                ('is_abstract', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'compounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_file', models.TextField()),
                ('included_refid', models.TextField(blank=True, null=True)),
                ('is_local', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'includes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('argsstring', models.TextField(blank=True, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('protection', models.TextField(blank=True, null=True)),
                ('is_static', models.IntegerField(default=0)),
                ('is_const', models.IntegerField(default=0)),
                ('is_constexpr', models.IntegerField(default=0)),
                ('is_virtual', models.IntegerField(default=0)),
                ('is_inline', models.IntegerField(default=0)),
                ('is_explicit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
            ],
            options={
                'db_table': 'namespaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('default_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymbolRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_member_refid', models.TextField()),
                ('to_member_name', models.TextField()),
                ('relationship', models.TextField()),
            ],
            options={
                'db_table': 'symbol_refs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OntologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_refid', models.CharField(blank=True, default='', help_text='Refid linking to a compound in the codebase DB', max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('class', 'Class'), ('struct', 'Struct'), ('enum', 'Enum'), ('union', 'Union'), ('namespace', 'Namespace'), ('interface', 'Interface'), ('concept', 'Design Concept')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('qualified_name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ontology_nodes',
            },
        ),
        migrations.CreateModel(
            name='OntologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('inherits', 'Inherits'), ('composes', 'Composes'), ('aggregates', 'Aggregates'), ('depends_on', 'Depends On'), ('calls', 'Calls'), ('implements', 'Implements'), ('uses', 'Uses')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='codebase.ontologynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='codebase.ontologynode')),
            ],
            options={
                'db_table': 'ontology_edges',
                'unique_together': {('source', 'target', 'relationship')},
            },
        ),
    ]
