# Generated by Django 6.0.3 on 2026-03-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodebaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('path', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('base_classes', models.TextField(blank=True, null=True)),
                ('is_final', models.IntegerField(default=0)),
                ('is_abstract', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'compounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_file', models.TextField()),
                ('included_refid', models.TextField(blank=True, null=True)),
                ('is_local', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'includes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('argsstring', models.TextField(blank=True, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('protection', models.TextField(blank=True, null=True)),
                ('is_static', models.IntegerField(default=0)),
                ('is_const', models.IntegerField(default=0)),
                ('is_constexpr', models.IntegerField(default=0)),
                ('is_virtual', models.IntegerField(default=0)),
                ('is_inline', models.IntegerField(default=0)),
                ('is_explicit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('qualified_name', models.TextField()),
            ],
            options={
                'db_table': 'namespaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('default_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymbolRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_member_refid', models.TextField()),
                ('to_member_name', models.TextField()),
                ('relationship', models.TextField()),
            ],
            options={
                'db_table': 'symbol_refs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OntologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_refid', models.CharField(blank=True, default='', help_text='Refid linking to a compound in the codebase DB', max_length=200)),
                ('kind', models.CharField(choices=[('attribute', 'Attribute'), ('class', 'Class'), ('constant', 'Constant'), ('enum', 'Enum'), ('enum_value', 'Enum Value'), ('function', 'Function'), ('interface', 'Interface'), ('method', 'Method'), ('module', 'Module'), ('primitive', 'Primitive Type'), ('type_alias', 'Type Alias')], max_length=20)),
                ('specialization', models.CharField(blank=True, default='', help_text='Language-specific specialization (e.g., template_class, dataclass)', max_length=40)),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='', help_text='Access specifier (public/private/protected). Blank for nodes where N/A.', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('qualified_name', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ontology_nodes',
            },
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ontology_predicates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NamespaceNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codebase.ontologynode',),
        ),
        migrations.CreateModel(
            name='OntologyTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triples_as_object', to='codebase.ontologynode')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triples_as_subject', to='codebase.ontologynode')),
                ('predicate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triples', to='codebase.predicate')),
            ],
            options={
                'db_table': 'ontology_triples',
                'unique_together': {('subject', 'predicate', 'object')},
            },
        ),
    ]
