# Generated by Django 6.0.3 on 2026-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologynode',
            name='compound_refid',
            field=models.CharField(blank=True, default='', help_text='Refid linking to a compound in the codebase DB', max_length=200),
        ),
    ]
