# Generated by Django 6.0.3 on 2026-03-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0001_initial'),
        ('components', '0003_language_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologynode',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontology_nodes', to='components.component'),
        ),
        migrations.AddField(
            model_name='ontologynode',
            name='is_intercomponent',
            field=models.BooleanField(default=False, help_text='Public interface boundary for cross-component use'),
        ),
    ]
