# Generated by Django 6.0.3 on 2026-03-07 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0002_alter_ontologynode_compound_refid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=200)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triples_as_object', to='codebase.ontologynode')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triples_as_subject', to='codebase.ontologynode')),
            ],
            options={
                'db_table': 'ontology_triples',
                'unique_together': {('subject', 'predicate', 'object')},
            },
        ),
        migrations.DeleteModel(
            name='OntologyEdge',
        ),
    ]
