# Generated by Django 6.0.3 on 2026-03-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_ontologytriple_delete_ontologyedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamespaceNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('codebase.ontologynode',),
        ),
    ]
