"""add dependency_recommendations table

Revision ID: 1815cde91bd3
Revises: 4684793af51a
Create Date: 2026-03-25 17:21:26.669423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1815cde91bd3'
down_revision: Union[str, Sequence[str], None] = '4684793af51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('github_url', sa.String(length=500), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('version', sa.String(length=100), server_default='', nullable=False),
    sa.Column('stars', sa.Integer(), server_default='0', nullable=False),
    sa.Column('license', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_updated', sa.String(length=50), server_default='', nullable=False),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('relevant_hlrs', sa.JSON(), nullable=True),
    sa.Column('relevant_structures', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_dependency_recommendations_component_id_components'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_recommendations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_recommendations')
    # ### end Alembic commands ###
