"""initial schema

Revision ID: 386b62adeef5
Revises: 
Create Date: 2026-03-15 17:42:37.395199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386b62adeef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build_systems', 'language_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('build_systems_language_id_ea5b0776'), table_name='build_systems')
    op.drop_constraint(None, 'build_systems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_build_systems_language_id_languages'), 'build_systems', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('components', 'parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('components', 'language_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('components_language_id_a49a0c7e'), table_name='components')
    op.drop_index(op.f('components_parent_id_b68ef128'), table_name='components')
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.create_foreign_key(op.f('fk_components_language_id_languages'), 'components', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_components_parent_id_components'), 'components', 'components', ['parent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dependencies', 'manager_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('dependencies_manager_id_0a96b4bf'), table_name='dependencies')
    op.drop_constraint(None, 'dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dependencies_manager_id_dependency_managers'), 'dependencies', 'dependency_managers', ['manager_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dependency_managers', 'language_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('dependency_managers_language_id_55ddd339'), table_name='dependency_managers')
    op.drop_constraint(None, 'dependency_managers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dependency_managers_language_id_languages'), 'dependency_managers', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('high_level_requirements', 'component_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('high_level_requirements', 'dependency_context',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('high_level_requirements_component_id_ca39d554'), table_name='high_level_requirements')
    op.drop_constraint(None, 'high_level_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_high_level_requirements_component_id_components'), 'high_level_requirements', 'components', ['component_id'], ['id'], ondelete='SET NULL')
    op.alter_column('high_level_requirements_triples', 'highlevelrequirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('high_level_requirements_triples', 'ontologytriple_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('high_level_requirements_triples_highlevelrequirement_id_a59cc5a8'), table_name='high_level_requirements_triples')
    op.drop_index(op.f('high_level_requirements_triples_highlevelrequirement_id_ontologytriple_id_a13e6ea6_uniq'), table_name='high_level_requirements_triples')
    op.drop_index(op.f('high_level_requirements_triples_ontologytriple_id_0f97ee98'), table_name='high_level_requirements_triples')
    op.drop_constraint(None, 'high_level_requirements_triples', type_='foreignkey')
    op.drop_constraint(None, 'high_level_requirements_triples', type_='foreignkey')
    op.create_foreign_key(op.f('fk_high_level_requirements_triples_ontologytriple_id_ontology_triples'), 'high_level_requirements_triples', 'ontology_triples', ['ontologytriple_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_high_level_requirements_triples_highlevelrequirement_id_high_level_requirements'), 'high_level_requirements_triples', 'high_level_requirements', ['highlevelrequirement_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_languages_name'), 'languages', ['name'])
    op.alter_column('low_level_requirements', 'high_level_requirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('low_level_requirements_high_level_requirement_id_d294bfd8'), table_name='low_level_requirements')
    op.drop_constraint(None, 'low_level_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_low_level_requirements_high_level_requirement_id_high_level_requirements'), 'low_level_requirements', 'high_level_requirements', ['high_level_requirement_id'], ['id'], ondelete='SET NULL')
    op.alter_column('low_level_requirements_components', 'lowlevelrequirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('low_level_requirements_components', 'component_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('low_level_requirements_components_component_id_8183535b'), table_name='low_level_requirements_components')
    op.drop_index(op.f('low_level_requirements_components_lowlevelrequirement_id_005e10c3'), table_name='low_level_requirements_components')
    op.drop_index(op.f('low_level_requirements_components_lowlevelrequirement_id_component_id_c5d21475_uniq'), table_name='low_level_requirements_components')
    op.drop_constraint(None, 'low_level_requirements_components', type_='foreignkey')
    op.drop_constraint(None, 'low_level_requirements_components', type_='foreignkey')
    op.create_foreign_key(op.f('fk_low_level_requirements_components_lowlevelrequirement_id_low_level_requirements'), 'low_level_requirements_components', 'low_level_requirements', ['lowlevelrequirement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_low_level_requirements_components_component_id_components'), 'low_level_requirements_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.alter_column('low_level_requirements_triples', 'lowlevelrequirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('low_level_requirements_triples', 'ontologytriple_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('low_level_requirements_triples_lowlevelrequirement_id_3a6dc4e8'), table_name='low_level_requirements_triples')
    op.drop_index(op.f('low_level_requirements_triples_lowlevelrequirement_id_ontologytriple_id_d7fd64ab_uniq'), table_name='low_level_requirements_triples')
    op.drop_index(op.f('low_level_requirements_triples_ontologytriple_id_0decda69'), table_name='low_level_requirements_triples')
    op.drop_constraint(None, 'low_level_requirements_triples', type_='foreignkey')
    op.drop_constraint(None, 'low_level_requirements_triples', type_='foreignkey')
    op.create_foreign_key(op.f('fk_low_level_requirements_triples_lowlevelrequirement_id_low_level_requirements'), 'low_level_requirements_triples', 'low_level_requirements', ['lowlevelrequirement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_low_level_requirements_triples_ontologytriple_id_ontology_triples'), 'low_level_requirements_triples', 'ontology_triples', ['ontologytriple_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ontology_nodes', 'component_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ontology_nodes_component_id_ece0da7f'), table_name='ontology_nodes')
    op.drop_constraint(None, 'ontology_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ontology_nodes_component_id_components'), 'ontology_nodes', 'components', ['component_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_ontology_predicates_name'), 'ontology_predicates', ['name'])
    op.alter_column('ontology_triples', 'subject_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ontology_triples', 'predicate_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ontology_triples', 'object_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ontology_triples_object_id_0be0088a'), table_name='ontology_triples')
    op.drop_index(op.f('ontology_triples_predicate_id_3e0b16e3'), table_name='ontology_triples')
    op.drop_index(op.f('ontology_triples_subject_id_67a97449'), table_name='ontology_triples')
    op.drop_index(op.f('ontology_triples_subject_id_predicate_id_object_id_88a43625_uniq'), table_name='ontology_triples')
    op.create_unique_constraint('uq_ontology_triples_subject_predicate_object', 'ontology_triples', ['subject_id', 'predicate_id', 'object_id'])
    op.drop_constraint(None, 'ontology_triples', type_='foreignkey')
    op.drop_constraint(None, 'ontology_triples', type_='foreignkey')
    op.drop_constraint(None, 'ontology_triples', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ontology_triples_subject_id_ontology_nodes'), 'ontology_triples', 'ontology_nodes', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ontology_triples_object_id_ontology_nodes'), 'ontology_triples', 'ontology_nodes', ['object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ontology_triples_predicate_id_ontology_predicates'), 'ontology_triples', 'ontology_predicates', ['predicate_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('test_frameworks', 'language_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('test_frameworks_language_id_4dc36cfc'), table_name='test_frameworks')
    op.drop_constraint(None, 'test_frameworks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_test_frameworks_language_id_languages'), 'test_frameworks', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_acceptance_criteria', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ticket_acceptance_criteria_ticket_id_5de36e6d'), table_name='ticket_acceptance_criteria')
    op.drop_constraint(None, 'ticket_acceptance_criteria', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_acceptance_criteria_ticket_id_tickets'), 'ticket_acceptance_criteria', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_files', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ticket_files_ticket_id_a4a80a1e'), table_name='ticket_files')
    op.drop_constraint(None, 'ticket_files', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_files_ticket_id_tickets'), 'ticket_files', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_references', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ticket_references_ticket_id_77bafb59'), table_name='ticket_references')
    op.drop_constraint(None, 'ticket_references', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_references_ticket_id_tickets'), 'ticket_references', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_requirements', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('ticket_requirements', 'low_level_requirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ticket_requirements_low_level_requirement_id_9e08ee86'), table_name='ticket_requirements')
    op.drop_index(op.f('ticket_requirements_ticket_id_59443ced'), table_name='ticket_requirements')
    op.drop_index(op.f('ticket_requirements_ticket_id_low_level_requirement_id_dac30489_uniq'), table_name='ticket_requirements')
    op.create_unique_constraint('uq_ticket_requirements_ticket_llr', 'ticket_requirements', ['ticket_id', 'low_level_requirement_id'])
    op.drop_constraint(None, 'ticket_requirements', type_='foreignkey')
    op.drop_constraint(None, 'ticket_requirements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ticket_requirements_low_level_requirement_id_low_level_requirements'), 'ticket_requirements', 'low_level_requirements', ['low_level_requirement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ticket_requirements_ticket_id_tickets'), 'ticket_requirements', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('tickets_parent_id_d0d81430'), table_name='tickets')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_parent_id_tickets'), 'tickets', 'tickets', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tickets_components', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('tickets_components', 'component_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('tickets_components_component_id_78216060'), table_name='tickets_components')
    op.drop_index(op.f('tickets_components_ticket_id_a1f23e17'), table_name='tickets_components')
    op.drop_index(op.f('tickets_components_ticket_id_component_id_055f7e18_uniq'), table_name='tickets_components')
    op.drop_constraint(None, 'tickets_components', type_='foreignkey')
    op.drop_constraint(None, 'tickets_components', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_components_ticket_id_tickets'), 'tickets_components', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_components_component_id_components'), 'tickets_components', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets_languages', 'ticket_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('tickets_languages', 'language_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('tickets_languages_language_id_694c7506'), table_name='tickets_languages')
    op.drop_index(op.f('tickets_languages_ticket_id_6fa3640c'), table_name='tickets_languages')
    op.drop_index(op.f('tickets_languages_ticket_id_language_id_01d78d09_uniq'), table_name='tickets_languages')
    op.drop_constraint(None, 'tickets_languages', type_='foreignkey')
    op.drop_constraint(None, 'tickets_languages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_languages_ticket_id_tickets'), 'tickets_languages', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_languages_language_id_languages'), 'tickets_languages', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_actions', 'verification_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('verification_actions', 'ontology_node_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('verification_actions_ontology_node_id_7a5b3632'), table_name='verification_actions')
    op.drop_index(op.f('verification_actions_verification_id_f4b64910'), table_name='verification_actions')
    op.drop_constraint(None, 'verification_actions', type_='foreignkey')
    op.drop_constraint(None, 'verification_actions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_verification_actions_ontology_node_id_ontology_nodes'), 'verification_actions', 'ontology_nodes', ['ontology_node_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_verification_actions_verification_id_verification_methods'), 'verification_actions', 'verification_methods', ['verification_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_conditions', 'verification_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('verification_conditions', 'ontology_node_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('verification_conditions_ontology_node_id_13a6c63d'), table_name='verification_conditions')
    op.drop_index(op.f('verification_conditions_verification_id_582e599e'), table_name='verification_conditions')
    op.drop_constraint(None, 'verification_conditions', type_='foreignkey')
    op.drop_constraint(None, 'verification_conditions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_verification_conditions_ontology_node_id_ontology_nodes'), 'verification_conditions', 'ontology_nodes', ['ontology_node_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_verification_conditions_verification_id_verification_methods'), 'verification_conditions', 'verification_methods', ['verification_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verification_methods', 'low_level_requirement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('verification_methods_low_level_requirement_id_c3978177'), table_name='verification_methods')
    op.drop_constraint(None, 'verification_methods', type_='foreignkey')
    op.create_foreign_key(op.f('fk_verification_methods_low_level_requirement_id_low_level_requirements'), 'verification_methods', 'low_level_requirements', ['low_level_requirement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_verification_methods_low_level_requirement_id_low_level_requirements'), 'verification_methods', type_='foreignkey')
    op.create_foreign_key(None, 'verification_methods', 'low_level_requirements', ['low_level_requirement_id'], ['id'])
    op.create_index(op.f('verification_methods_low_level_requirement_id_c3978177'), 'verification_methods', ['low_level_requirement_id'], unique=False)
    op.alter_column('verification_methods', 'low_level_requirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_verification_conditions_verification_id_verification_methods'), 'verification_conditions', type_='foreignkey')
    op.drop_constraint(op.f('fk_verification_conditions_ontology_node_id_ontology_nodes'), 'verification_conditions', type_='foreignkey')
    op.create_foreign_key(None, 'verification_conditions', 'ontology_nodes', ['ontology_node_id'], ['id'])
    op.create_foreign_key(None, 'verification_conditions', 'verification_methods', ['verification_id'], ['id'])
    op.create_index(op.f('verification_conditions_verification_id_582e599e'), 'verification_conditions', ['verification_id'], unique=False)
    op.create_index(op.f('verification_conditions_ontology_node_id_13a6c63d'), 'verification_conditions', ['ontology_node_id'], unique=False)
    op.alter_column('verification_conditions', 'ontology_node_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('verification_conditions', 'verification_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_verification_actions_verification_id_verification_methods'), 'verification_actions', type_='foreignkey')
    op.drop_constraint(op.f('fk_verification_actions_ontology_node_id_ontology_nodes'), 'verification_actions', type_='foreignkey')
    op.create_foreign_key(None, 'verification_actions', 'ontology_nodes', ['ontology_node_id'], ['id'])
    op.create_foreign_key(None, 'verification_actions', 'verification_methods', ['verification_id'], ['id'])
    op.create_index(op.f('verification_actions_verification_id_f4b64910'), 'verification_actions', ['verification_id'], unique=False)
    op.create_index(op.f('verification_actions_ontology_node_id_7a5b3632'), 'verification_actions', ['ontology_node_id'], unique=False)
    op.alter_column('verification_actions', 'ontology_node_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('verification_actions', 'verification_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_tickets_languages_language_id_languages'), 'tickets_languages', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_languages_ticket_id_tickets'), 'tickets_languages', type_='foreignkey')
    op.create_foreign_key(None, 'tickets_languages', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'tickets_languages', 'tickets', ['ticket_id'], ['id'])
    op.create_index(op.f('tickets_languages_ticket_id_language_id_01d78d09_uniq'), 'tickets_languages', ['ticket_id', 'language_id'], unique=1)
    op.create_index(op.f('tickets_languages_ticket_id_6fa3640c'), 'tickets_languages', ['ticket_id'], unique=False)
    op.create_index(op.f('tickets_languages_language_id_694c7506'), 'tickets_languages', ['language_id'], unique=False)
    op.alter_column('tickets_languages', 'language_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('tickets_languages', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_tickets_components_component_id_components'), 'tickets_components', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_components_ticket_id_tickets'), 'tickets_components', type_='foreignkey')
    op.create_foreign_key(None, 'tickets_components', 'components', ['component_id'], ['id'])
    op.create_foreign_key(None, 'tickets_components', 'tickets', ['ticket_id'], ['id'])
    op.create_index(op.f('tickets_components_ticket_id_component_id_055f7e18_uniq'), 'tickets_components', ['ticket_id', 'component_id'], unique=1)
    op.create_index(op.f('tickets_components_ticket_id_a1f23e17'), 'tickets_components', ['ticket_id'], unique=False)
    op.create_index(op.f('tickets_components_component_id_78216060'), 'tickets_components', ['component_id'], unique=False)
    op.alter_column('tickets_components', 'component_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('tickets_components', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_tickets_parent_id_tickets'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'tickets', ['parent_id'], ['id'])
    op.create_index(op.f('tickets_parent_id_d0d81430'), 'tickets', ['parent_id'], unique=False)
    op.alter_column('tickets', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_ticket_requirements_ticket_id_tickets'), 'ticket_requirements', type_='foreignkey')
    op.drop_constraint(op.f('fk_ticket_requirements_low_level_requirement_id_low_level_requirements'), 'ticket_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_requirements', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'ticket_requirements', 'low_level_requirements', ['low_level_requirement_id'], ['id'])
    op.drop_constraint('uq_ticket_requirements_ticket_llr', 'ticket_requirements', type_='unique')
    op.create_index(op.f('ticket_requirements_ticket_id_low_level_requirement_id_dac30489_uniq'), 'ticket_requirements', ['ticket_id', 'low_level_requirement_id'], unique=1)
    op.create_index(op.f('ticket_requirements_ticket_id_59443ced'), 'ticket_requirements', ['ticket_id'], unique=False)
    op.create_index(op.f('ticket_requirements_low_level_requirement_id_9e08ee86'), 'ticket_requirements', ['low_level_requirement_id'], unique=False)
    op.alter_column('ticket_requirements', 'low_level_requirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ticket_requirements', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_ticket_references_ticket_id_tickets'), 'ticket_references', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_references', 'tickets', ['ticket_id'], ['id'])
    op.create_index(op.f('ticket_references_ticket_id_77bafb59'), 'ticket_references', ['ticket_id'], unique=False)
    op.alter_column('ticket_references', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_ticket_files_ticket_id_tickets'), 'ticket_files', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_files', 'tickets', ['ticket_id'], ['id'])
    op.create_index(op.f('ticket_files_ticket_id_a4a80a1e'), 'ticket_files', ['ticket_id'], unique=False)
    op.alter_column('ticket_files', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_ticket_acceptance_criteria_ticket_id_tickets'), 'ticket_acceptance_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_acceptance_criteria', 'tickets', ['ticket_id'], ['id'])
    op.create_index(op.f('ticket_acceptance_criteria_ticket_id_5de36e6d'), 'ticket_acceptance_criteria', ['ticket_id'], unique=False)
    op.alter_column('ticket_acceptance_criteria', 'ticket_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_test_frameworks_language_id_languages'), 'test_frameworks', type_='foreignkey')
    op.create_foreign_key(None, 'test_frameworks', 'languages', ['language_id'], ['id'])
    op.create_index(op.f('test_frameworks_language_id_4dc36cfc'), 'test_frameworks', ['language_id'], unique=False)
    op.alter_column('test_frameworks', 'language_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_ontology_triples_predicate_id_ontology_predicates'), 'ontology_triples', type_='foreignkey')
    op.drop_constraint(op.f('fk_ontology_triples_object_id_ontology_nodes'), 'ontology_triples', type_='foreignkey')
    op.drop_constraint(op.f('fk_ontology_triples_subject_id_ontology_nodes'), 'ontology_triples', type_='foreignkey')
    op.create_foreign_key(None, 'ontology_triples', 'ontology_predicates', ['predicate_id'], ['id'])
    op.create_foreign_key(None, 'ontology_triples', 'ontology_nodes', ['object_id'], ['id'])
    op.create_foreign_key(None, 'ontology_triples', 'ontology_nodes', ['subject_id'], ['id'])
    op.drop_constraint('uq_ontology_triples_subject_predicate_object', 'ontology_triples', type_='unique')
    op.create_index(op.f('ontology_triples_subject_id_predicate_id_object_id_88a43625_uniq'), 'ontology_triples', ['subject_id', 'predicate_id', 'object_id'], unique=1)
    op.create_index(op.f('ontology_triples_subject_id_67a97449'), 'ontology_triples', ['subject_id'], unique=False)
    op.create_index(op.f('ontology_triples_predicate_id_3e0b16e3'), 'ontology_triples', ['predicate_id'], unique=False)
    op.create_index(op.f('ontology_triples_object_id_0be0088a'), 'ontology_triples', ['object_id'], unique=False)
    op.alter_column('ontology_triples', 'object_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ontology_triples', 'predicate_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ontology_triples', 'subject_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_ontology_predicates_name'), 'ontology_predicates', type_='unique')
    op.drop_constraint(op.f('fk_ontology_nodes_component_id_components'), 'ontology_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'ontology_nodes', 'components', ['component_id'], ['id'])
    op.create_index(op.f('ontology_nodes_component_id_ece0da7f'), 'ontology_nodes', ['component_id'], unique=False)
    op.alter_column('ontology_nodes', 'component_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_low_level_requirements_triples_ontologytriple_id_ontology_triples'), 'low_level_requirements_triples', type_='foreignkey')
    op.drop_constraint(op.f('fk_low_level_requirements_triples_lowlevelrequirement_id_low_level_requirements'), 'low_level_requirements_triples', type_='foreignkey')
    op.create_foreign_key(None, 'low_level_requirements_triples', 'low_level_requirements', ['lowlevelrequirement_id'], ['id'])
    op.create_foreign_key(None, 'low_level_requirements_triples', 'ontology_triples', ['ontologytriple_id'], ['id'])
    op.create_index(op.f('low_level_requirements_triples_ontologytriple_id_0decda69'), 'low_level_requirements_triples', ['ontologytriple_id'], unique=False)
    op.create_index(op.f('low_level_requirements_triples_lowlevelrequirement_id_ontologytriple_id_d7fd64ab_uniq'), 'low_level_requirements_triples', ['lowlevelrequirement_id', 'ontologytriple_id'], unique=1)
    op.create_index(op.f('low_level_requirements_triples_lowlevelrequirement_id_3a6dc4e8'), 'low_level_requirements_triples', ['lowlevelrequirement_id'], unique=False)
    op.alter_column('low_level_requirements_triples', 'ontologytriple_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('low_level_requirements_triples', 'lowlevelrequirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_low_level_requirements_components_component_id_components'), 'low_level_requirements_components', type_='foreignkey')
    op.drop_constraint(op.f('fk_low_level_requirements_components_lowlevelrequirement_id_low_level_requirements'), 'low_level_requirements_components', type_='foreignkey')
    op.create_foreign_key(None, 'low_level_requirements_components', 'low_level_requirements', ['lowlevelrequirement_id'], ['id'])
    op.create_foreign_key(None, 'low_level_requirements_components', 'components', ['component_id'], ['id'])
    op.create_index(op.f('low_level_requirements_components_lowlevelrequirement_id_component_id_c5d21475_uniq'), 'low_level_requirements_components', ['lowlevelrequirement_id', 'component_id'], unique=1)
    op.create_index(op.f('low_level_requirements_components_lowlevelrequirement_id_005e10c3'), 'low_level_requirements_components', ['lowlevelrequirement_id'], unique=False)
    op.create_index(op.f('low_level_requirements_components_component_id_8183535b'), 'low_level_requirements_components', ['component_id'], unique=False)
    op.alter_column('low_level_requirements_components', 'component_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('low_level_requirements_components', 'lowlevelrequirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_low_level_requirements_high_level_requirement_id_high_level_requirements'), 'low_level_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'low_level_requirements', 'high_level_requirements', ['high_level_requirement_id'], ['id'])
    op.create_index(op.f('low_level_requirements_high_level_requirement_id_d294bfd8'), 'low_level_requirements', ['high_level_requirement_id'], unique=False)
    op.alter_column('low_level_requirements', 'high_level_requirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_languages_name'), 'languages', type_='unique')
    op.drop_constraint(op.f('fk_high_level_requirements_triples_highlevelrequirement_id_high_level_requirements'), 'high_level_requirements_triples', type_='foreignkey')
    op.drop_constraint(op.f('fk_high_level_requirements_triples_ontologytriple_id_ontology_triples'), 'high_level_requirements_triples', type_='foreignkey')
    op.create_foreign_key(None, 'high_level_requirements_triples', 'high_level_requirements', ['highlevelrequirement_id'], ['id'])
    op.create_foreign_key(None, 'high_level_requirements_triples', 'ontology_triples', ['ontologytriple_id'], ['id'])
    op.create_index(op.f('high_level_requirements_triples_ontologytriple_id_0f97ee98'), 'high_level_requirements_triples', ['ontologytriple_id'], unique=False)
    op.create_index(op.f('high_level_requirements_triples_highlevelrequirement_id_ontologytriple_id_a13e6ea6_uniq'), 'high_level_requirements_triples', ['highlevelrequirement_id', 'ontologytriple_id'], unique=1)
    op.create_index(op.f('high_level_requirements_triples_highlevelrequirement_id_a59cc5a8'), 'high_level_requirements_triples', ['highlevelrequirement_id'], unique=False)
    op.alter_column('high_level_requirements_triples', 'ontologytriple_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('high_level_requirements_triples', 'highlevelrequirement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_high_level_requirements_component_id_components'), 'high_level_requirements', type_='foreignkey')
    op.create_foreign_key(None, 'high_level_requirements', 'components', ['component_id'], ['id'])
    op.create_index(op.f('high_level_requirements_component_id_ca39d554'), 'high_level_requirements', ['component_id'], unique=False)
    op.alter_column('high_level_requirements', 'dependency_context',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('high_level_requirements', 'component_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_dependency_managers_language_id_languages'), 'dependency_managers', type_='foreignkey')
    op.create_foreign_key(None, 'dependency_managers', 'languages', ['language_id'], ['id'])
    op.create_index(op.f('dependency_managers_language_id_55ddd339'), 'dependency_managers', ['language_id'], unique=False)
    op.alter_column('dependency_managers', 'language_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_dependencies_manager_id_dependency_managers'), 'dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'dependencies', 'dependency_managers', ['manager_id'], ['id'])
    op.create_index(op.f('dependencies_manager_id_0a96b4bf'), 'dependencies', ['manager_id'], unique=False)
    op.alter_column('dependencies', 'manager_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_components_parent_id_components'), 'components', type_='foreignkey')
    op.drop_constraint(op.f('fk_components_language_id_languages'), 'components', type_='foreignkey')
    op.create_foreign_key(None, 'components', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'components', 'components', ['parent_id'], ['id'])
    op.create_index(op.f('components_parent_id_b68ef128'), 'components', ['parent_id'], unique=False)
    op.create_index(op.f('components_language_id_a49a0c7e'), 'components', ['language_id'], unique=False)
    op.alter_column('components', 'language_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('components', 'parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_build_systems_language_id_languages'), 'build_systems', type_='foreignkey')
    op.create_foreign_key(None, 'build_systems', 'languages', ['language_id'], ['id'])
    op.create_index(op.f('build_systems_language_id_ea5b0776'), 'build_systems', ['language_id'], unique=False)
    op.alter_column('build_systems', 'language_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
