"""add description to components

Revision ID: 4684793af51a
Revises: cb7b8dcb2b4d
Create Date: 2026-03-25 05:47:09.621777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4684793af51a'
down_revision: Union[str, Sequence[str], None] = 'cb7b8dcb2b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('description', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'description')
    # ### end Alembic commands ###
