"""add dependency indexing config fields

Revision ID: 57e489149179
Revises: f726bb8d906d
Create Date: 2026-03-30 19:48:36.348019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e489149179'
down_revision: Union[str, Sequence[str], None] = 'f726bb8d906d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('index_file_patterns', sa.String(length=200), server_default='*.h *.hpp', nullable=False))
    op.add_column('dependencies', sa.Column('index_subdir', sa.String(length=200), server_default='', nullable=False))
    op.add_column('dependencies', sa.Column('index_exclude_patterns', sa.String(length=500), server_default='', nullable=False))
    op.add_column('dependencies', sa.Column('index_recursive', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependencies', 'index_recursive')
    op.drop_column('dependencies', 'index_exclude_patterns')
    op.drop_column('dependencies', 'index_subdir')
    op.drop_column('dependencies', 'index_file_patterns')
    # ### end Alembic commands ###
