"""Add github_url to dependencies

Revision ID: 92888bdb877b
Revises: c1f5629eb758
Create Date: 2026-03-29 11:59:54.333618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92888bdb877b'
down_revision: Union[str, Sequence[str], None] = 'c1f5629eb758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('github_url', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependencies', 'github_url')
    # ### end Alembic commands ###
