"""add namespace to components

Revision ID: cb7b8dcb2b4d
Revises: d2bda3c4ae65
Create Date: 2026-03-25 05:24:01.808876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7b8dcb2b4d'
down_revision: Union[str, Sequence[str], None] = 'd2bda3c4ae65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('namespace', sa.String(length=200), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'namespace')
    # ### end Alembic commands ###
