"""add requirement nodes association tables

Revision ID: ead4b30f9296
Revises: 5a8ed9234b3b
Create Date: 2026-05-19 10:47:48.268125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead4b30f9296'
down_revision: Union[str, Sequence[str], None] = '5a8ed9234b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_level_requirements_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('highlevelrequirement_id', sa.Integer(), nullable=False),
    sa.Column('ontologynode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['highlevelrequirement_id'], ['high_level_requirements.id'], name=op.f('fk_high_level_requirements_nodes_highlevelrequirement_id_high_level_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ontologynode_id'], ['ontology_nodes.id'], name=op.f('fk_high_level_requirements_nodes_ontologynode_id_ontology_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_high_level_requirements_nodes'))
    )
    op.create_table('low_level_requirements_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lowlevelrequirement_id', sa.Integer(), nullable=False),
    sa.Column('ontologynode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lowlevelrequirement_id'], ['low_level_requirements.id'], name=op.f('fk_low_level_requirements_nodes_lowlevelrequirement_id_low_level_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ontologynode_id'], ['ontology_nodes.id'], name=op.f('fk_low_level_requirements_nodes_ontologynode_id_ontology_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_low_level_requirements_nodes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('low_level_requirements_nodes')
    op.drop_table('high_level_requirements_nodes')
    # ### end Alembic commands ###
