"""add dependency_components association table

Revision ID: f726bb8d906d
Revises: 92888bdb877b
Create Date: 2026-03-29 13:34:08.845175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f726bb8d906d'
down_revision: Union[str, Sequence[str], None] = '92888bdb877b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_components',
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_dependency_components_component_id_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], name=op.f('fk_dependency_components_dependency_id_dependencies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependency_id', 'component_id', name=op.f('pk_dependency_components'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_components')
    # ### end Alembic commands ###
