"""HLR CRUD, decomposition, and requirements dashboard data — migrated backend.

Uses neomodel objects (HLR, LLR, VerificationMethod, Component) for
requirement traversal and ``CodeGraphNode.serialize()`` for dict
production.  Cross-cutting aggregate counts (total design-graph nodes,
total triples) use raw Cypher via ``codegraph.connection.get_session``
since they span the entire codegraph.

The COMPOSES hierarchy:

  Component → HLR → LLR → VerificationMethod

mirrors the codegraph LayerGraph composition pattern (Namespace → Class
→ Method).  Neomodel relationship managers (``.llrs.all()``,
``.component.all()``, etc.) replace raw Cypher traversal.

Identity via ``refid``
~~~~~~~~~~~~~~~~~~~~~~~
HLR, LLR, VerificationMethod, Condition, and Action all override
``CodeGraphNode.refid`` as ``UniqueIdProperty()`` (same pattern as
``FileNode`` in the codegraph).  This makes ``refid`` the canonical
unique identifier — auto-generated by neomodel on ``.save()`` and
enforced by a Neo4j uniqueness constraint.  The ``id`` key in
serialised dicts is set to ``refid`` so that the UI can use it as
a row key and navigation target.

Neomodel initialisation
~~~~~~~~~~~~~~~~~~~~~~~~
Neomodel auto-initialises its database driver on first query via a
decorator on ``cypher_query``.  No explicit ``_ensure_driver()`` call
is needed before neomodel operations (``.nodes.all()``, ``.save()``,
``.delete()``).  For raw Cypher through ``get_session()``, the
``codegraph.connection`` module handles driver initialisation
internally.

No imports from backend/ anywhere in this module.
"""

from __future__ import annotations

import logging

from backend_migrated.models import Component, HLR, LLR, VerificationMethod

log = logging.getLogger(__name__)


def _get_session():
    """Return a Neo4j session context manager from the shared connection pool.

    Used only for cross-cutting aggregate counts that span the entire
    codegraph and cannot be expressed as neomodel queries on a single
    node type.  ``get_session`` calls ``_ensure_driver`` internally.
    """
    from codegraph.connection import get_session
    return get_session()


# ---------------------------------------------------------------------------
# Requirements dashboard data
# ---------------------------------------------------------------------------


def fetch_requirements_data() -> dict:
    """Fetch all data needed for the requirements dashboard.

    Uses neomodel objects for HLR/LLR/VM traversal and
    ``CodeGraphNode.serialize()`` for dict production.  The ``id`` key
    in each dict is set to the node's ``refid`` (UniqueIdProperty).

    Returns a dict with keys:
      hlrs              — list of serialized HLR dicts (with llrs and component)
      unlinked_llrs     — list of serialized LLR dicts with no parent HLR
      total_hlrs        — number of HLR nodes
      total_llrs        — number of LLR nodes
      total_verifications — number of VerificationMethod nodes
      total_nodes       — number of design-graph nodes (CompoundNode, MemberNode, NamespaceNode)
      total_triples     — number of design-graph edges
    """
    # --- HLRs and their LLRs via neomodel ---
    all_hlrs = HLR.nodes.all()
    hlrs: list[dict] = []

    for hlr in all_hlrs:
        hlr_data = hlr.serialize(fields="all", nested=True)

        llr_nodes = hlr.llrs.all()
        hlr_data["llrs"] = [l.serialize(fields="all", nested=True) for l in llr_nodes]

        comp_nodes = hlr.component.all()
        hlr_data["component"] = comp_nodes[0].name if comp_nodes else None

        hlrs.append(hlr_data)

    # --- Unlinked LLRs (no parent HLR via COMPOSES) ---
    all_llrs = LLR.nodes.all()
    linked_refids: set[str] = set()
    for hlr in all_hlrs:
        for llr in hlr.llrs.all():
            linked_refids.add(llr.refid)

    unlinked_llrs: list[dict] = []
    for llr in all_llrs:
        if llr.refid not in linked_refids:
            unlinked_llrs.append(llr.serialize(fields="all", nested=True))

    # --- Aggregate counts ---
    total_verifications = len(VerificationMethod.nodes.all())

    # Design-graph counts span all code-level node types — use raw Cypher.
    with _get_session() as ns:
        total_nodes = ns.run(
            "MATCH (d) WHERE d:CompoundNode OR d:MemberNode OR d:NamespaceNode RETURN count(d) AS cnt"
        ).single()["cnt"]

        total_triples = ns.run(
            "MATCH (s)-[r]->(t) "
            "WHERE (s:CompoundNode OR s:MemberNode OR s:NamespaceNode) "
            "AND (t:CompoundNode OR t:MemberNode OR t:NamespaceNode) "
            "RETURN count(r) AS cnt"
        ).single()["cnt"]

    return {
        "hlrs": hlrs,
        "unlinked_llrs": unlinked_llrs,
        "total_hlrs": len(hlrs),
        "total_llrs": len(all_llrs),
        "total_verifications": total_verifications,
        "total_nodes": total_nodes,
        "total_triples": total_triples,
    }


# ---------------------------------------------------------------------------
# HLR detail / CRUD — still stubs (to be migrated later)
# ---------------------------------------------------------------------------


def fetch_hlr_detail(refid: str) -> dict | None:
    """Fetch all data needed for HLR detail page.

    Uses neomodel objects for HLR/LLR/VM traversal and
    ``CodeGraphNode.serialize()`` for dict production.
    Returns ``None`` if the HLR is not found.
    """
    hlr = HLR.nodes.get_or_none(refid=refid)
    if not hlr:
        return None

    hlr_data = hlr.serialize(fields="all", nested=True)

    llr_nodes = hlr.llrs.all()
    hlr_data["llrs"] = [l.serialize(fields="all", nested=True) for l in llr_nodes]

    comp_nodes = hlr.component.all()
    hlr_data["component"] = comp_nodes[0].name if comp_nodes else None
    hlr_data["component_id"] = getattr(comp_nodes[0], "refid", None) if comp_nodes else None

    return hlr_data


def create_hlr(description: str, component_name: str | None = None) -> str:
    """Create a new HLR in Neo4j. Returns the new HLR's refid.

    Uses ``CodeGraphNode.save_new()`` to validate, construct, and persist
    the node in one call.  If *component_name* is given, a COMPOSES edge
    from the Component to the new HLR is created.
    """
    hlr = HLR.save_new(description=description, layer="design")

    if component_name:
        comp = Component.nodes.get_or_none(name=component_name)
        if comp:
            comp.requirements.connect(hlr)

    log.info("Created HLR refid=%s description=%r", hlr.refid, description)
    return hlr.refid


def update_hlr(refid: str, description: str, component_name: str | None = None) -> bool:
    """Update an HLR's description and component in Neo4j. Returns True on success.

    Uses ``CodeGraphNode.update()`` to persist property changes.
    If *component_name* is provided, the old COMPOSES edge (if any) is
    removed and a new one is created.
    """
    hlr = HLR.nodes.get_or_none(refid=refid)
    if not hlr:
        return False

    hlr.update(description=description)

    if component_name is not None:
        # Remove old COMPOSES edges from any Component
        for comp in hlr.component.all():
            comp.requirements.disconnect(hlr)

        # Create new COMPOSES edge if component_name is non-empty
        if component_name:
            comp = Component.nodes.get_or_none(name=component_name)
            if comp:
                comp.requirements.connect(hlr)

    return True


def delete_hlr(refid: str) -> bool:
    """Delete an HLR and its COMPOSES subtree from Neo4j. Returns True on success.

    ``CodeGraphNode.delete()`` cascades through all outgoing COMPOSES
    children (depth-first, leaves first), disconnects remaining
    relationships, then removes the node.
    """
    hlr = HLR.nodes.get_or_none(refid=refid)
    if not hlr:
        return False

    hlr.delete()
    return True


def decompose_hlr(refid: str) -> dict:
    """Run the decomposition agent on an HLR and persist results to Neo4j.

    Reads the HLR and sibling HLRs from Neo4j, calls the LLM-based
    ``decompose()`` function, then persists the resulting LLRs and
    verification methods using neomodel models.

    Returns a dict with keys:
      llrs_created        — number of LLRs created
      verifications_created — number of VerificationMethods created
    """
    import os

    from backend_migrated.models import Condition as Cond
    from backend_migrated.models import Action as Act
    from backend_migrated.agents.decompose_hlr import decompose

    log_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "logs")
    os.makedirs(log_dir, exist_ok=True)
    prompt_log_file = os.path.join(log_dir, f"decompose_hlr_{refid}_raw.txt")

    hlr = HLR.nodes.get_or_none(refid=refid)
    if not hlr:
        raise ValueError(f"HLR {refid} not found")
    hlr_description = hlr.description

    # dependency_context is a legacy property that may not be on every node
    dep_ctx = getattr(hlr, "dependency_context", None)

    # Get the HLR's component name
    comp_nodes = hlr.component.all()
    component_name = comp_nodes[0].name if comp_nodes else ""

    # Run decomposition agent
    decomposed = decompose(
        description=hlr_description,
        component=component_name,
        dependency_context=dep_ctx,
        prompt_log_file=prompt_log_file,
    )

    log.info(
        "Decomposition of HLR %s produced %d LLRs",
        refid[:8],
        len(decomposed.low_level_requirements),
    )
    for i, llr_data in enumerate(decomposed.low_level_requirements):
        log.info(
            "  LLR[%d]: %s (verifications=%d)",
            i,
            llr_data.description[:80],
            len(llr_data.verifications),
        )

    # Persist results using neomodel models.
    # Each LLR/VM/Condition/Action is saved individually so that a single
    # bad record doesn't abort the entire batch — partial progress is
    # better than losing everything.
    llrs_created = 0
    verifications_created = 0
    errors: list[str] = []

    for li, llr_data in enumerate(decomposed.low_level_requirements):
        try:
            llr = LLR.save_new(description=llr_data.description, layer="design")
        except Exception as exc:
            log.error("Failed to save LLR[%d]: %s", li, exc, exc_info=True)
            errors.append(f"LLR[{li}]: {exc}")
            continue

        try:
            hlr.llrs.connect(llr)
        except Exception as exc:
            log.warning("Failed to connect LLR[%d] to HLR: %s", li, exc)
            # Still count the LLR — it exists even if the edge failed

        llrs_created += 1
        log.info("Saved LLR[%d] refid=%s", li, llr.refid[:8])

        for vi, v in enumerate(llr_data.verifications):
            try:
                vm = VerificationMethod.save_new(
                    method=v["method"],
                    test_name=v.get("test_name", "") or "",
                    description=v.get("description", "") or "",
                    layer="design",
                )
                llr.verification_methods.connect(vm)
                verifications_created += 1
                log.info("Saved VM[%d] for LLR[%d] refid=%s", vi, li, vm.refid[:8])
            except Exception as exc:
                log.error(
                    "Failed to save VM[%d] for LLR[%d]: %s", vi, li, exc, exc_info=True,
                )
                errors.append(f"LLR[{li}].VM[{vi}]: {exc}")
                continue

            for i, cond in enumerate(v.get("preconditions", [])):
                try:
                    c = Cond.save_new(
                        phase="pre",
                        order=i,
                        operator=cond["operator"],
                        expected_value=cond.get("expected_value", cond.get("expected", "")),
                        subject_qualified_name=cond["subject_qualified_name"],
                        object_qualified_name=cond.get("object_qualified_name", ""),
                        layer="design",
                    )
                    vm.conditions.connect(c)
                except Exception as exc:
                    log.warning("Failed to save precondition[%d] for LLR[%d].VM[%d]: %s", i, li, vi, exc)

            for i, action in enumerate(v.get("actions", [])):
                try:
                    a = Act.save_new(
                        order=i,
                        description=action["description"],
                        caller_qualified_name=action.get("caller_qualified_name", ""),
                        callee_qualified_name=action.get("callee_qualified_name", ""),
                        layer="design",
                    )
                    vm.actions.connect(a)
                except Exception as exc:
                    log.warning("Failed to save action[%d] for LLR[%d].VM[%d]: %s", i, li, vi, exc)

            for i, cond in enumerate(v.get("postconditions", [])):
                try:
                    c = Cond.save_new(
                        phase="post",
                        order=i,
                        operator=cond["operator"],
                        expected_value=cond.get("expected_value", cond.get("expected", "")),
                        subject_qualified_name=cond["subject_qualified_name"],
                        object_qualified_name=cond.get("object_qualified_name", ""),
                        layer="design",
                    )
                    vm.conditions.connect(c)
                except Exception as exc:
                    log.warning("Failed to save postcondition[%d] for LLR[%d].VM[%d]: %s", i, li, vi, exc)

    if errors:
        log.warning(
            "Decomposition completed with %d errors: %s",
            len(errors),
            "; ".join(errors[:5]),
        )

    return {
        "llrs_created": llrs_created,
        "verifications_created": verifications_created,
    }


def design_single_hlr(refid: str) -> dict:
    """Run the design agent on an HLR and persist the ontology results.

    Delegates to ``design_and_persist_hlr`` in
    ``backend_migrated.agents.design_hlr`` which handles context
    loading, pipeline execution, and persistence.

    Returns dict with keys ``nodes_created``, ``triples_created``,
    ``links_applied``.
    """
    import os
    from backend_migrated.agents.design_hlr import design_and_persist_hlr

    log_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "logs"
    )
    os.makedirs(log_dir, exist_ok=True)

    return design_and_persist_hlr(refid=refid, log_dir=log_dir)