# Generated by Django 6.0.3 on 2026-03-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codebase', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(help_text="Human-readable description (e.g., 'Press the + button')")),
                ('member_qualified_name', models.CharField(blank=True, help_text='Specific member invoked (e.g., calc::gui::OperatorButton::onClick)', max_length=500)),
            ],
            options={
                'db_table': 'verification_actions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'Pre-condition'), ('post', 'Post-condition')], max_length=4)),
                ('order', models.PositiveIntegerField(default=0)),
                ('member_qualified_name', models.CharField(help_text='Fully qualified member name (e.g., calc::core::Calculator::operation)', max_length=500)),
                ('operator', models.CharField(choices=[('==', 'equals'), ('!=', 'not equals'), ('<', 'less than'), ('>', 'greater than'), ('<=', 'less than or equal'), ('>=', 'greater than or equal'), ('is_true', 'is true'), ('is_false', 'is false'), ('contains', 'contains'), ('not_null', 'is not null')], default='==', max_length=20)),
                ('expected_value', models.CharField(help_text='Expected value or state (e.g., Operation::Addition)', max_length=500)),
            ],
            options={
                'db_table': 'verification_conditions',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('automated', 'Automated'), ('review', 'Review'), ('inspection', 'Inspection')], max_length=20)),
                ('test_name', models.CharField(blank=True, help_text="Test that verifies this (e.g., 'test_press_addition_key')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Free-text summary of what this verification does')),
            ],
            options={
                'db_table': 'verification_methods',
            },
        ),
        migrations.CreateModel(
            name='HighLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('triples', models.ManyToManyField(blank=True, help_text='Ontology triples that express this requirement', related_name='high_level_requirements', to='codebase.ontologytriple')),
            ],
            options={
                'db_table': 'high_level_requirements',
            },
        ),
        migrations.CreateModel(
            name='LowLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('components', models.ManyToManyField(blank=True, help_text='Components that implement this requirement', related_name='low_level_requirements', to='components.component')),
                ('high_level_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_level_requirements', to='requirements.highlevelrequirement')),
                ('triples', models.ManyToManyField(blank=True, help_text='Ontology triples that express this requirement', related_name='low_level_requirements', to='codebase.ontologytriple')),
            ],
            options={
                'db_table': 'low_level_requirements',
            },
        ),
        migrations.CreateModel(
            name='TicketRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_level_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.lowlevelrequirement')),
            ],
            options={
                'db_table': 'ticket_requirements',
            },
        ),
    ]
