# Generated by Django 6.0.3 on 2026-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlevelrequirement',
            name='action',
            field=models.CharField(default='', help_text="What they do (e.g., 'compiles')", max_length=200),
        ),
        migrations.AddField(
            model_name='highlevelrequirement',
            name='actor',
            field=models.CharField(default='', help_text="Who performs the action (e.g., 'a developer')", max_length=200),
        ),
        migrations.AddField(
            model_name='highlevelrequirement',
            name='subject',
            field=models.CharField(default='', help_text="What they act on (e.g., 'the codebase')", max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='action',
            field=models.CharField(default='', help_text="What they do (e.g., 'presses the + button')", max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='actor',
            field=models.CharField(default='', help_text="Who performs the action (e.g., 'the end user')", max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Components that implement this requirement', related_name='low_level_requirements', to='components.component'),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='confirmation',
            field=models.TextField(blank=True, help_text="How the behavior is confirmed (e.g., 'the operator field is populated with the ADDITION enum value')"),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='subject',
            field=models.CharField(default='', help_text="What they act on (e.g., 'in the GUI')", max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='test_name',
            field=models.CharField(blank=True, help_text="Test that verifies this requirement (e.g., 'user_presses_addition_key')", max_length=300),
        ),
        migrations.AlterField(
            model_name='highlevelrequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lowlevelrequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
