# Generated by Django 6.0.3 on 2026-03-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codebase', '0001_initial'),
        ('requirements', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequirement',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='verificationaction',
            name='ontology_node',
            field=models.ForeignKey(blank=True, help_text='Design entity being acted upon (e.g., OperatorButton)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codebase.ontologynode'),
        ),
        migrations.AddField(
            model_name='verificationcondition',
            name='ontology_node',
            field=models.ForeignKey(blank=True, help_text='Owning class/struct in the ontology graph', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codebase.ontologynode'),
        ),
        migrations.AddField(
            model_name='verificationmethod',
            name='low_level_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='requirements.lowlevelrequirement'),
        ),
        migrations.AddField(
            model_name='verificationcondition',
            name='verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='requirements.verificationmethod'),
        ),
        migrations.AddField(
            model_name='verificationaction',
            name='verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='requirements.verificationmethod'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketrequirement',
            unique_together={('ticket', 'low_level_requirement')},
        ),
    ]
