# Generated by Django 6.0.3 on 2026-03-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlevelrequirement',
            name='dependency_context',
            field=models.JSONField(blank=True, help_text='Dependency assessment from the assess_dependencies agent', null=True),
        ),
    ]
