# Generated by Django 6.0.3 on 2026-03-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_highlevelrequirement_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='verification',
        ),
        migrations.CreateModel(
            name='LLRVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('automated', 'Automated'), ('review', 'Review'), ('inspection', 'Inspection')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('low_level_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='requirements.lowlevelrequirement')),
            ],
            options={
                'db_table': 'llr_verifications',
            },
        ),
    ]
