# Generated by Django 6.0.3 on 2026-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_remove_lowlevelrequirement_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llrverification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='test_name',
        ),
        migrations.AddField(
            model_name='llrverification',
            name='confirmation',
            field=models.TextField(blank=True, help_text="How the behavior is confirmed (e.g., 'the operator field is populated with the ADDITION enum value')"),
        ),
        migrations.AddField(
            model_name='llrverification',
            name='test_name',
            field=models.CharField(blank=True, help_text="Test that verifies this (e.g., 'user_presses_addition_key')", max_length=300),
        ),
    ]
