# Generated by Django 6.0.3 on 2026-03-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_remove_llrverification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlevelrequirement',
            name='actor_compound_refid',
            field=models.CharField(blank=True, default='', help_text='Refid of a codebase compound acting as actor', max_length=200),
        ),
        migrations.AddField(
            model_name='highlevelrequirement',
            name='subject_compound_refid',
            field=models.CharField(blank=True, default='', help_text='Refid of a codebase compound acting as subject', max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='actor_compound_refid',
            field=models.CharField(blank=True, default='', help_text='Refid of a codebase compound acting as actor', max_length=200),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='subject_compound_refid',
            field=models.CharField(blank=True, default='', help_text='Refid of a codebase compound acting as subject', max_length=200),
        ),
    ]
