# Generated by Django 6.0.3 on 2026-03-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_ontologytriple_delete_ontologyedge'),
        ('requirements', '0005_highlevelrequirement_actor_compound_refid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlevelrequirement',
            name='actor_compound_refid',
        ),
        migrations.RemoveField(
            model_name='highlevelrequirement',
            name='subject_compound_refid',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='actor_compound_refid',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='subject_compound_refid',
        ),
        migrations.AddField(
            model_name='highlevelrequirement',
            name='triples',
            field=models.ManyToManyField(blank=True, help_text='Ontology triples that express this requirement', related_name='high_level_requirements', to='codebase.ontologytriple'),
        ),
        migrations.AddField(
            model_name='lowlevelrequirement',
            name='triples',
            field=models.ManyToManyField(blank=True, help_text='Ontology triples that express this requirement', related_name='low_level_requirements', to='codebase.ontologytriple'),
        ),
    ]
