# Generated by Django 6.0.3 on 2026-03-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_remove_highlevelrequirement_actor_compound_refid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlevelrequirement',
            name='action',
        ),
        migrations.RemoveField(
            model_name='highlevelrequirement',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='highlevelrequirement',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='action',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='lowlevelrequirement',
            name='subject',
        ),
        migrations.AlterField(
            model_name='highlevelrequirement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lowlevelrequirement',
            name='description',
            field=models.TextField(),
        ),
    ]
