# Generated by Django 6.0.3 on 2026-03-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0004_namespacenode'),
        ('requirements', '0007_remove_actor_action_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llrverification',
            name='confirmation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='llrverification',
            name='low_level_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_verifications', to='requirements.lowlevelrequirement'),
        ),
        migrations.AlterField(
            model_name='llrverification',
            name='test_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='VerificationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('automated', 'Automated'), ('review', 'Review'), ('inspection', 'Inspection')], max_length=20)),
                ('test_name', models.CharField(blank=True, help_text="Test that verifies this (e.g., 'test_press_addition_key')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Free-text summary of what this verification does')),
                ('low_level_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='requirements.lowlevelrequirement')),
            ],
            options={
                'db_table': 'verification_methods',
            },
        ),
        migrations.CreateModel(
            name='VerificationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'Pre-condition'), ('post', 'Post-condition')], max_length=4)),
                ('order', models.PositiveIntegerField(default=0)),
                ('member_qualified_name', models.CharField(help_text='Fully qualified member name (e.g., calc::core::Calculator::operation)', max_length=500)),
                ('operator', models.CharField(choices=[('==', 'equals'), ('!=', 'not equals'), ('<', 'less than'), ('>', 'greater than'), ('<=', 'less than or equal'), ('>=', 'greater than or equal'), ('is_true', 'is true'), ('is_false', 'is false'), ('contains', 'contains'), ('not_null', 'is not null')], default='==', max_length=20)),
                ('expected_value', models.CharField(help_text='Expected value or state (e.g., Operation::Addition)', max_length=500)),
                ('ontology_node', models.ForeignKey(blank=True, help_text='Owning class/struct in the ontology graph', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codebase.ontologynode')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='requirements.verificationmethod')),
            ],
            options={
                'db_table': 'verification_conditions',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(help_text="Human-readable description (e.g., 'Press the + button')")),
                ('member_qualified_name', models.CharField(blank=True, help_text='Specific member invoked (e.g., calc::gui::OperatorButton::onClick)', max_length=500)),
                ('ontology_node', models.ForeignKey(blank=True, help_text='Design entity being acted upon (e.g., OperatorButton)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codebase.ontologynode')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='requirements.verificationmethod')),
            ],
            options={
                'db_table': 'verification_actions',
                'ordering': ['order'],
            },
        ),
    ]
