# Generated by Django 6.0.3 on 2026-03-10 01:01

from django.db import migrations


def migrate_verifications(apps, schema_editor):
    """Copy LLRVerification rows into VerificationMethod."""
    LLRVerification = apps.get_model("requirements", "LLRVerification")
    VerificationMethod = apps.get_model("requirements", "VerificationMethod")

    for old in LLRVerification.objects.all():
        VerificationMethod.objects.create(
            low_level_requirement=old.low_level_requirement,
            method=old.method,
            test_name=old.test_name,
            description=old.confirmation,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_alter_llrverification_confirmation_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_verifications, migrations.RunPython.noop),
    ]
