# Generated by Django 6.0.3 on 2026-03-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DependencyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manifest_file', models.CharField(max_length=255)),
                ('lock_file', models.CharField(blank=True, max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_managers', to='components.language')),
            ],
            options={
                'db_table': 'dependency_managers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_file', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_systems', to='components.language')),
            ],
            options={
                'db_table': 'build_systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_file', models.CharField(max_length=255)),
                ('test_discovery_path', models.CharField(blank=True, max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_frameworks', to='components.language')),
            ],
            options={
                'db_table': 'test_frameworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('is_dev', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='components.dependencymanager')),
            ],
            options={
                'db_table': 'dependencies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('manager', 'name'), name='unique_dependency_per_manager')],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='components.component')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environment_components', to='components.language')),
            ],
            options={
                'db_table': 'components',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'parent'), name='unique_component_name_per_parent')],
            },
        ),
    ]
