# Generated by Django 6.0.3 on 2026-03-15 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('is_dev', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='components.dependencymanager')),
            ],
            options={
                'db_table': 'dependencies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('manager', 'name'), name='unique_dependency_per_manager')],
            },
        ),
    ]
