# Generated by Django 6.0.3 on 2026-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
