# Generated by Django 6.0.3 on 2026-03-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'high_level_requirements',
            },
        ),
        migrations.CreateModel(
            name='LowLevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('verification', models.CharField(choices=[('automated', 'Automated'), ('review', 'Review'), ('inspection', 'Inspection')], default='review', max_length=20)),
                ('high_level_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_level_requirements', to='tickets.highlevelrequirement')),
            ],
            options={
                'db_table': 'low_level_requirements',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('complexity', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('ticket_type', models.CharField(default='feature', max_length=50)),
                ('target_components', models.CharField(blank=True, max_length=500, null=True)),
                ('languages', models.CharField(default='C++', max_length=200)),
                ('requires_math', models.BooleanField(default=False)),
                ('generate_tutorial', models.BooleanField(default=False)),
                ('last_modified', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketAcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_criteria', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_acceptance_criteria',
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('change_type', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_files',
            },
        ),
        migrations.CreateModel(
            name='TicketReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_target', models.CharField(max_length=200)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_references',
            },
        ),
        migrations.CreateModel(
            name='TicketRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_level_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.lowlevelrequirement')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_requirements',
                'unique_together': {('ticket', 'low_level_requirement')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='low_level_requirements',
            field=models.ManyToManyField(blank=True, related_name='tickets', through='tickets.TicketRequirement', to='tickets.lowlevelrequirement'),
        ),
    ]
