# Generated by Django 6.0.3 on 2026-03-10 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
                ('complexity', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('ticket_type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('task', 'Task')], default='feature', max_length=50)),
                ('requires_math', models.BooleanField(default=False)),
                ('generate_tutorial', models.BooleanField(default=False)),
                ('components', models.ManyToManyField(blank=True, related_name='tickets', to='components.component')),
                ('languages', models.ManyToManyField(blank=True, related_name='tickets', to='components.language')),
                ('low_level_requirements', models.ManyToManyField(blank=True, related_name='tickets', through='requirements.TicketRequirement', to='requirements.lowlevelrequirement')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketAcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_criteria', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_acceptance_criteria',
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('change_type', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_files',
            },
        ),
        migrations.CreateModel(
            name='TicketReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_target', models.CharField(max_length=200)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_references',
            },
        ),
    ]
